### PR TITLE
Fixes #33 and prevents another NullPointerException on modulePath

### LINKED ISSUE #33: NullPointerException on create-runtime-image goal whith no goals specified
When using the `create-runtime-image` goal with no `<modules>` set, a NullPointerException is thrown at https://github.com/moditect/moditect/blob/e0b3fa191baacf8e201d9dadbc555cf3e27867cb/core/src/main/java/org/moditect/commands/CreateRuntimeImage.java#L68

That line should first check wether modules have been set before adding the `--add-modules` parameter.

### PR DESCRIPTION
**Pull request by ggam**

### CODE REVIEW

File: maven-plugin/src/main/java/org/moditect/mavenplugin/image/CreateRuntimeImageMojo.java [hunk 1]
```diff
@@ -35,13 +35,13 @@
 @Mojo(name = "create-runtime-image", defaultPhase = LifecyclePhase.PACKAGE)
 public class CreateRuntimeImageMojo extends AbstractMojo {
 
-    @Parameter
+    @Parameter(defaultValue = "[]")
```
Comment (ggam) [inline maven-plugin/src/main/java/org/moditect/mavenplugin/image/CreateRuntimeImageMojo.java]: This is to prevent another exception when no module paths are set. It's not really required since it internally adds the $JAVA_HOME module path to the user provided list.

**Comment by gunnarmorling** [comment]
Merged; I've only added one more commit to move the parameter check to the time of instantiation and to get rid of some trailing whitespace.

Thanks a lot, @ggam!

**Comment by ggam** [comment]
Makes sense, thanks!
