### PR TITLE
#222 Use ZipFile API to set timestamps

### LINKED ISSUE #222: Generated JAR file depends on default time zone
When Moditect adds elements to an existing JAR file, it uses `ZipFileSystem` instead of the older `ZipOutputStream`. Unfortunately this has a big drawback:

* JARs generated on systems that **only** differ by the setting of the default time zone are **not** identical.

The reason behind this is due to JDK internals:

* The old `ZipEntry#setTime/setLastModifiedTime` methods use [`java.util.zip.ZipUtils#javaToExtendedDosTime`](https://github.com/openjdk/jdk/blob/34351b7a7950a3b563748f40f2619374f62f9b16/src/java.base/share/classes/java/util/zip/ZipUtils.java#L155) method, which is **independent** from the system default time zone,
* The new `ZipFileSystem` on the other hand uses [`jdk.nio.zipfs.ZipUtils#javaToDosTime`](https://github.com/openjdk/jdk/blob/34351b7a7950a3b563748f40f2619374f62f9b16/src/jdk.zipfs/share/classes/jdk/nio/zipfs/ZipUtils.java#L238) method, which **depends** on the system default time zone.

## Reproduction

To reproduce this problem use any recent project that uses Moditect, e.g. [apache/commons-logging](https://github.com/apache/commons-logging) and build it using two different time zones.

On my Debian system with JDK 17 I obtain:

```sh
piotr@bialykiel:~/workspace/commons-logging$ git checkout rel/commons-logging-1.3.0
...
piotr@bialykiel:~/workspace/commons-logging$ export TZ=Europe/Warsaw
piotr@bialykiel:~/workspace/commons-logging$ mvn clean package
...
piotr@bialykiel:~/workspace/commons-logging$ sha256sum target/commons-logging-1.3.0.jar 
8590cef7d2810aef40334472696e11e3c0c97d6230a3eacaf685e74dc982d5ae  target/commons-logging-1.3.0.jar
piotr@bialykiel:~/workspace/commons-logging$ export TZ=America/Chicago
piotr@bialykiel:~/workspace/commons-logging$ mvn clean package
...
piotr@bialykiel:~/workspace/commons-logging$ sha256sum target/commons-logging-1.3.0.jar 
63ed3b7e92347ffe895d58ab72484af700c132e26206d6a4811d48d9f5c9462d  target/commons-logging-1.3.0.jar
```

The only difference is in the DOS time stamp of the entries modified by Moditect.

### PR DESCRIPTION
**Pull request by aalmiray**
Fixes #222

### CODE REVIEW

**Comment by aalmiray** [comment]
@hboutemy Here's the first attempt

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java [hunk 1]
```diff
@@ -99,62 +101,65 @@ public void run() {
...
+            if (jvmVersion != null) {
+                outputEntry = new JarEntry("META-INF/versions/" + jvmVersion + "/module-info.class");
             }
+            outputEntry.setTime(lastModifiedTime);
+            jarout.putNextEntry(outputEntry);
+            jarout.write(clazz, 0, clazz.length);
+            jarout.closeEntry();
         }
         catch (IOException e) {
+            e.printStackTrace();
```
Comment (ppkarwasz) [inline core/src/main/java/org/moditect/commands/AddModuleInfo.java:162]: This should probably not be there.

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java [hunk 2]
```diff
@@ -99,62 +101,65 @@ public void run() {
...
 
-                manifest.getMainAttributes().put(new Attributes.Name("Multi-Release"), "true");
-                try (OutputStream manifestOs = Files.newOutputStream(manifestPath, StandardOpenOption.TRUNCATE_EXISTING)) {
-                    manifest.write(manifestOs);
-                }
-                setTimes(manifestPath, lastModifiedTime);
+            // copy module descriptor
+            JarEntry outputEntry = new JarEntry("module-info.class");
+            if (jvmVersion != null) {
+                outputEntry = new JarEntry("META-INF/versions/" + jvmVersion + "/module-info.class");
```
Comment (ppkarwasz) [inline core/src/main/java/org/moditect/commands/AddModuleInfo.java:154]: Unconditionally appending `module-info.class` at the end of the JAR can lead to problems if the original JAR already contains a `module-info.class`.

This can happen in practice if the user runs the build twice and `AddModuleInfo` is executed twice in a row.

**Review by ppkarwasz — APPROVED** [review]
Looks good to me, except some small remarks.

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java (hunk 1 above)
Comment (aalmiray) [reply core/src/main/java/org/moditect/commands/AddModuleInfo.java:162]: Oops, yeah. Will remove it.

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java (hunk 2 above)
Comment (aalmiray) [reply core/src/main/java/org/moditect/commands/AddModuleInfo.java:154]: Indeed, good catch. Removing any existing entries for the descriptor should also solve https://github.com/moditect/moditect/issues/215

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java (hunk 1 above)
Comment (aalmiray) [reply core/src/main/java/org/moditect/commands/AddModuleInfo.java]: done

File: core/src/main/java/org/moditect/commands/AddModuleInfo.java (hunk 2 above)
Comment (aalmiray) [reply core/src/main/java/org/moditect/commands/AddModuleInfo.java]: done

**Review by ppkarwasz — APPROVED** [review]
LGTM
